# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOS-Categories-DevApp' do
	
	pod 'iOS-Categories/Foundation/NSString', :path => '../'

end

target 'iOS-Categories-DevAppTests' do

end

